# Site settings
title: Painbird | A Dev log
description: "Web App Project."
url: "https://painbird.github.io"
author:
  name: "HyeongJin"
  email: "painbirdz@gmail.com"
  url: "https://painbird.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site

#permalink: /:title
#paginate: 8
#paginate_path: /page:num/

# Paginate config
pagination:
  enabled: true
  per_page: 8
  sort_reverse: true
  title: ':title'
  permalink: '/page:num'
  trail: 
    before: 1
    after: 1

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate-v2
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
